### ISSUE TITLE
Strike or Base components - What's recommended?

### ISSUE THREAD

**Issue by up2go-rsoesemann** [appiphony/Strike-Components#112]
With Winter '18 Salesforce.com released a bunch of new Lightning Base Components. Components that we were desperately missing half a year ago. Back then Strike Components where our rescue.

Now we face the question is we should evaluate and replace Strike components with native `lightning:xyz` components.

What's the best way to handle this? As Strike is mainly backed by Appiphony a Salesforce-backed company, I expect them to align their roadmap with Salesforce and also can recommend how to reduce redundant work.

A few components I am unsure in Winter'18 are:
 - `strike:modal` vs. `lightning:overlayLibrary`
 - `lightning:progressIndicator` vs. https://github.com/appiphony/Strike-Components/pull/61
 - `strike:datagrid` vs. `lightning:datatable`
 - `strike:accordion` vs. `lightning:accordion`
 - ...

Note: I also asked this question on StackExchange: https://salesforce.stackexchange.com/questions/196647

**Comment by georgekenessey** [comment]
@up2go-rsoesemann we are so glad to hear that Strike components were your rescue. It makes all the work we have put into them worth it when we hear comments like that. Please keep in mind that Strike components are a open source project that came out of our own needs for a set of Lightning components. To-date we have put in over 5,000 plus hours into making them. We thought it would be great to share them with other developers as a way to give back. Yes, we are funded by Salesforce but I want to make it clear to all that we are in no way coordinating our roadmap for Strike components with the Salesforce Lighting team. We base our roadmap on the challenges we are facing in our projects and if we need a solution immediately or can afford to wait for a future Salesforce release when a component may become available.

We have not made decisions yet as to what changes we will make due to all the awesome new components being released in Winter 18. Over the next few releases we will evaluate how to best approach the scenario when a new Base component is released by Salesforce that is the equivalent of a Strike component. I suspect that there will be times when we require a component to have some functionality that Salesforce Base components do not support and in those cases we will will be able to make the decision to add it to an existing Strike component or build our own version of the component. We see a world where there is a benefit to multiple choices existing side-by-side. Data Grid is a good example. There are a multitude of open source grid/table projects because the use cases for them vary so much. I imagine Salesforce would struggle supporting them all with the new Datatable component. In situations like this the Strike Data Grid may have a role to still play.

At the end of the day every one has a different situation they are facing and I hope that sharing some of our thinking helps in some way. Take care.

**Comment by up2go-rsoesemann** [comment]
Thanks @georgekenessey for this detailed insight and answer. Can I also share this on StackExchange?

**Comment by georgekenessey** [comment]
@up2go-rsoesemann Yes, please feel free to.
