### ISSUE TITLE
Can't pre-populate Multipicker with saved data

### ISSUE THREAD

**Issue by TomSesselmann** [appiphony/Strike-Components#12]
After I make a selection in the Multipicker and save the data, when I refresh, the Multipicker appears blank, there are no pill's displayed and the options that should already be selected are still available in the list.

**Comment by kevinberonilla** [comment]
Hello @TomSesselmann, you should be able to achieve this by populating the `value` attribute of the component with the saved data. This attribute accepts a semi-colon-separated string representing the selected options' values. An example would be:

```html
<aura:attribute name="savedData" type="String"/> <!-- Run code that sets the value of this attribute to something like "option-1;option-3" -->

<c:strike_multiSelectPicklist
    label="My Multi Select Picklist"
    value="{!v.savedData}" >
        <c:strike_option label="Option 1" value="option-1"/>
        <c:strike_option label="Option 2" value="option-2"/>
        <c:strike_option label="Option 3" value="option-3"/>
</c:strike_multiSelectPicklist>
```

Please let me know if this solution works for you.

**Comment by TomSesselmann** [comment]
Thanks @kevinberonilla the value attribute was set correctly but I found out that the `savedData` handn't finished loading when the multiSelectPicklist was initialised so technically the value was null. To solve this I wrapped the component with `<aura:if isTrue="{! savedData  != null}">` so that the component only intialises after the `savedData` has finished loading.

Sorry if this is trivial, but I'm still quite new to lightning development :)

I have encountered another issue which I think is more legitimate though, so I'll create a seperate issue ticket. This one can be closed.

**Comment by kevinberonilla** [comment]
We try our best to help out since we were also new to Lightning at some point, and we know all too well it's not easy to jump into. Another idea for your solution would be to have a handler on `init` like so:
`<aura:handler name="init" value="{!this}" action="{!c.onInit}"/>`xml

The `onInit` controller method would prepare the `value` string and set it with `component.set('v.savedData', 'option-1;option-3');`javascript which should trigger a rerender on your component, adding the selected pills.
