### ISSUE TITLE
strike_expandableSection component

### ISSUE THREAD

**Issue by dsharrison** [appiphony/Strike-Components#138]
Salesforce added a `lightning:accordion` and `lightning:accordionSection` in Winter 18. However, these do now allow for a single section to be expanded/collapsed. It would be great if we also had an implementation of the [expandable section](https://lightningdesignsystem.com/components/expandable-section/#content).

**Comment by daneowens3** [comment]
at the moment we don't have this on our radar. however, we will be adding a fiddler for the accordion soon. closing for now with the possibility that we'll implement such a component in the future.

**Comment by dsharrison** [comment]
No worries. Our team is considering developing this component for our internal use. If we choose to do so do you think this aligns with what Strike is trying to offer? (If so I would open a PR).

**Comment by georgekenessey** [comment]
@dsharrison first off thanks for using Strike and your support. Since Strike came out of our need for components in our client work that is always our test for adding a new component. As of now we have not come across any use cases that need a more sophisticated accordion than for our clients than what Salesforce's base accordion component offers (not to say this may not happen in the future). We have not done PRs on entire components to-date because we are trying to be very conscious of the time required to maintain the existing set. The components we have written all follow similar patterns which helps when maintaining them. Our main fear around doing a PR on a component that we have not written is that it would just be different enough from the rest that it would make maintaining the whole set more complicated. We would be happy to consider your PR but you may try and pattern is after other components we have written to increase the likely hood of us being able to pull it in. Hope that helps.
