### ISSUE TITLE
Is Strike still maintained and open to contributions?

### ISSUE THREAD

**Issue by rsoesemann** [appiphony/Strike-Components#212]
It doesn't feel so. It feels like people from Appiphony fix defects they need for internal projects but ignore stuff from outside. But the reactions and reaction time when I opened issues, and later fixed them in pull requests is frustrating. And it's confusing for people from outside who want to build on the code.

I know there is no guarantee with any Open Source. But this is not another small repo by an single developer. Appiphony promoted it actively and so did others (including myself). Can SalesforceDevs still rely on Strike components for development or not? 

FYI:  @georgekenessey

**Comment by georgekenessey** [comment]
@rsoesemann Thank you for posting the issue. I apologize about the delays you have experienced in regards to Appiphony accepting pull requests and we will strive to do better. I believe in full transparency so let me explain our perspective on the project and current situation in hopes that it will help you and others make an educated decision on if Strike is right for you.

Strike grew out of our own needs for a robust set of Lightning components for client work and it continues to be the main driver behind the project for us. We were fortunate to have some incredibly talented people available to spend thousands of hours on Strike and are very proud of the work they accomplished. In the end we decided to share it with the community and in full honesty did not completely appreciate the demands on our time this would take. 

We have been incredibly fortunate to experience a large growth in our business and are very committed to giving each and every one of our clients the highest quality of work we can provide. The downside is that lately we have simply had no bandwidth to work on Strike.

Our propencity toward delivering extreme quality does not always make addressing issues and pull requests related to Strike easy for us. When they exist, we treat each one as a project that needs to be planned, executed and delivered. For example, a pull request needs to be reviewed by a senior developer and they need to determine if it makes sense for it to be included in the project as a whole. Often this is discussed with a lead architect. A QA person then needs to test the change and update the documentation (often in collaboration with the developer). We also need to evaluate if modifying the correlating fiddler is necessary. Unfortunately for us it is not just a push of a button due to the level of documentation we have put around the components. This has certainly had it’s benefits but come at an obvious cost.

All I can say is that we will strive to do better and are hiring more folks to support our increased demand for services. We hope to spend more time on to the project and will prioritize our client needs when we do. Hopefully this insight helps you make an informed decision around the use of Strike and as always we appreciate your support.

**Comment by rsoesemann** [comment]
Depending on a costly architect for reviewing a few line of bug fix code might be an unrealistic expectation for an open source project. I wasn't talking about feature extension PRs. That can be done in forks.
