### ISSUE TITLE
strike:select not displayed properly in Lightning action modal

### ISSUE THREAD

**Issue by up2go-rsoesemann** [appiphony/Strike-Components#28]
I'm a CSS newbie, so this might be a trivial question. Nonetheless I need help.

I have this Lightning component used as action on a button.

    <aura:component controller="..." access="GLOBAL" implements="force:lightningQuickActionWithoutHeader,force:hasRecordId">
        <div class="slds-page-header" role="banner">
            <p class="slds-text-heading--label">{!v.record.Name}</p>
            <h1 class="slds-page-header__title slds-m-right--small slds-truncate slds-align-left">Add new year</h1>
        </div>
        
       <c:strike_select value="{!v.selected}" placeholder="Select Template" onchange="{!c.doSelect}">
            <aura:renderIf isTrue="{!v.showBlank}">
                <c:strike_option value="" label="No Template (Create blank record)" />
            </aura:renderIf>
            
            <aura:iteration items="{!v.templates}" var="tmpl">
                <c:strike_option value="{!tmpl.id}" label="{!tmpl.label}" />
            </aura:iteration>
        </c:strike_select>
        
        <lightning:button label="Cancel" onclick="{!c.doCancel}" variant="neutral"  />
        <lightning:button label="Continue" onclick="{!c.doContinue}" variant="brand" /> 
    </aura:component>

But as you see in the screenshots there are three display problems.

 1. The select **options are auto-opened** on page load
 2. The select **options are hidden** outside of the modal (showing 2 ugly scrollbars

[![enter image description here][2]][2]

  [1]: https://github.com/appiphony/Strike-Components
  [2]: https://i.stack.imgur.com/H938y.png
  [3]: https://i.stack.imgur.com/e4sYN.png

**Comment by kevinberonilla** [comment]
Hi @up2go-rsoesemann, 

Problem 1 is an interesting one. Right now it seems as though the `strike_select` is being focused when the modal opens. By design, the component is meant to show its options when focused on. Could you think of anything that might be something targeting the element on component init?

Problem 2 is a common issue we run into when using Lightning actions in modals. The key problem is that we're displaying dynamic content in a static frame; we only have access to adjust the modal's height as a setting, but not much else. The only solution I can think of besides adjusting the modal height to always have room to display the dropdown height is creating a `<style>` tag directly in the component to target the action modal's content (`.slds-modal__content`) and set it to `overflow: visible` or `overflow-y: visible`.

The style element is needed to break past the component CSS file's restrictions, where all selectors are scoped to the component namespace therefore you're only able to affect the component itself and its child elements. This solution will cause other problems though, such as selecting other action modals while in LEX. There have also been talks on no longer supporting style elements in the  future.

**Comment by up2go-rsoesemann** [comment]
**Problem 1**: In the component onInit I populate the selectOptions

```
doInit : function(cmp, event, helper) {    
        var action = cmp.get("c.getOptions");
      	action.setCallback(this, function(response) {
            cmp.set("v.options", response.getReturnValue());
	    });
	    
	    $A.enqueueAction(action); 
	    
	    cmp.find("strikeSelectAuraId").getElement().blur();
    },
```

But blurring the focus doesn't help. :-(

**Problem 2:** SOLVED. Thanks!

**Comment by kevinberonilla** [comment]
Can you please try adding a random `<lightning:input label="Name" name="myname" />` before the Strike Select as a test? I'm wondering if there is some sort of auto-focus being enforced from the outside for the first focusable element. If this is the case, the modal will open with the newly added input instead.

**Comment by up2go-rsoesemann** [comment]
That worked. But when I hide it with display:none or other CSS properties it won't work. Can't you think of a fix within your code?

**Comment by up2go-rsoesemann** [comment]
I could solve it by adding a <div tabindex="0" ></div> before my strike-select. Maybe this is something you can incorporate into your code.

**Comment by kevinberonilla** [comment]
Yes that input was just a test to confirm my suspicions, but now it seems like something with Quick Actions is enforcing the focus from the outside, which explains why your init trick didn't work.

I'll continue to think of a solution for this and keep you posted.
