### ISSUE TITLE
CSS issue for strike Lookup on IE11

### ISSUE THREAD

**Issue by vimalkarun** [appiphony/Strike-Components#42]
Strike lookup component is not rendered correctly on IE11. 
The component is displayed with Vertical and Horizontal Scroll Bar. The pull down menu for Search result is hidden behind the vertical scroll

![image](https://user-images.githubusercontent.com/7862438/28508625-a694f026-7059-11e7-8b29-fc721e6c5158.png)

![image](https://user-images.githubusercontent.com/7862438/28508634-b9ecaf06-7059-11e7-8045-41d20e50c58b.png)

**Comment by kevinberonilla** [comment]
Thanks for logging this! It turns out there were some extra classes used on the mobile version of the component that were not conditionally left out. This will be fixed in the next release, but if you need a solution for the current release (0.7.0), you can replace lines 114 and 115 in `strike_lookup.cmp` with the following code:

```
            <div class="{!'sl-lookup__input_container' + if(v.isMobile == true, ' slds-grid slds-grid--pull-padded-xx-small', '') + if(and(equals(v.initCallsRunning, 0), empty(v.value)), '', ' slds-hide')}">
                <div class="{!'sl-lookup__input' + if(v.isMobile == true, ' slds-col slds-p-horizontal--xx-small', '')}">
```

Padding negation using the `slds-grid--pull-padded` classes was causing the horizontal bar to appear on Edge in cases where the lookup's containing element did not have room for negative margins. Now, these classes are only applied if the `v.isMobile` internal attribute is set to `true`.

Please let us know if this solution works for you.

**Comment by vimalkarun** [comment]
Thank you for the solution, and now the horizontal scroll is not appearing which is good. but still the search result is hidden behind the vertical scroll. 

![image](https://user-images.githubusercontent.com/7862438/28654516-a1cd2bb6-72b2-11e7-96a6-2d25cdbbe6e9.png)


![image](https://user-images.githubusercontent.com/7862438/28654527-b5e2e9b0-72b2-11e7-8b81-5ce81041f977.png)

**Comment by kevinberonilla** [comment]
Odd, we'll look into it!

**Comment by kevinberonilla** [comment]
Hi @vimalkarun,

Can you try adding the following lines at the *end* of your CSS file (`strike_lookup.css`)?

```
.THIS:not(.sl-lookup--mobile).sl-lookup--open.scrollable {
    overflow: visible;
}

.THIS:not(.sl-lookup--mobile):not(.sl-lookup--open).scrollable {
    overflow: hidden;
}
```

Additionally, to fix a mobile issue that might be introduced by those rules, you can add the following line in the helper file (`strike_lookupHelper.js`) above line `150` (before `component.set('v.searching', true);`):

```
component.set('v.openMenu', true);
```

**Comment by vimalkarun** [comment]
Cool.. issue is fixed.. :)

**Comment by kevinberonilla** [comment]
If you don't mind, we'd like to keep this issue open until it's actually fixed (when the next release drops, which actually might be today). This is just to help QA keep track of fixes and build changelogs.

**Comment by vimalkarun** [comment]
@kevinberonilla I'm fine to keep it open, and ready to test it on next release changes.
