### ISSUE TITLE
Strike Input - If marked as required it should mark itself red on blur if input is empty

### ISSUE THREAD

**Issue by chewy2** [appiphony/Strike-Components#51]
Currently if you set a strike-input to required it doesn't do anything other than display the red star. It should go into an error state if the input is empty and the user blurs out of the input. Lightning-input does this, but we don't.

**Comment by DouglasCAyers** [comment]
This can be achieved with the `error` attribute to return `true` when the value is empty.

>  error="{!empty(v.foo)}"

Full example:

    <c:strike_input
        type="text"
        name="input-name"
        label="Foo"
        value="{!v.foo}"
        required="true"
        error="{!empty(v.foo)}"
        errorMessage="Foo is required"/>

The **required** attribute simply provides the visual indicator that the field is required, but validation is still whatever logic you need it to be.

**Comment by dsharrison** [comment]
I think that ideally we could get a cross between what @DouglasCAyers mentions above and the behavior from `lightning:input`. Its great that the lightning input variants automatically validate and show errors on blur and that their state can be checked via the `v.validity` attribute. However, adding custom validation and/or errors to them is tough because setting the `v.validity` object does not behave in a consistent way (and I don't think its really even supported?).

**Comment by daneowens3** [comment]
this will be added in the next release

**Comment by up2go-rsoesemann** [comment]
@daneowens3 Will those extension be also applied to other Strike components that have a required attribute? E.g. the Multiselect Picklist
