### ISSUE TITLE
The Strike modal is not on top

### ISSUE THREAD

**Issue by MasterOfPonio** [appiphony/Strike-Components#54]
The css style that comes with this component has to have the z-index equal to 0

**Comment by kevinberonilla** [comment]
Hi @MasterOfPonio,

Do you have an example of how the modal is being used and how its surrounding elements are styled? Our `strike_modal` component bundle does not come with a CSS file, so the markup we generate uses only SLDS's CSS classes.

This may be a bug that needs to be logged in the SLDS repo (https://github.com/salesforce-ux/design-system/issues).

**Comment by MasterOfPonio** [comment]
Hi @kevinberonilla 

The example is not mine, so I can't show the code. But it's a table lightning component, that has a button and that button opens the modal, which basically is a record view( so I've put a record view inside it ). 

`<force:recordView recordId="{!v.item.Id}" type="FULL"/>`

And after that I've set the aura footer buttons, to treat them.

I would find a great thing to have also the X button from above to treat it separately ,as right now it's making the modal to not open again( I wanted to put this thing as another issue - I personally bypassed it calling the init function by getting the element through the component.get command).

Well I think that every modal that you make should be set by default on top of other elements, so for me, it should come with the css file, otherwise I have to make a css file everytime I have to use it.

I don't know how changing your code works on your licence, I think it's not allowed, so I didn't modified anything in the appiphony code.

**Comment by kevinberonilla** [comment]
Modifying the code is allowed so long as the included license text is left untouched; please modify however you'd like. One thing to mention about modifications is that if you use our CLI to install newer versions to your org, your changes will be overwritten, so take caution with updating.

As for the CSS, we will consider adding your request in a future release but my initial reaction for these types of updates is concern for existing implementations of `strike_modal`. The effectiveness of `z-index`-related updates rely heavily on a plethora of conditions (where the element exists in the DOM tree, how their parent element's `position` is set to those of their siblings, etc.). We will definitely test to see if this update is intrusive in any way. Most of the time, our team solves these types of issues simply by moving the call for `<c:strike_modal>` elsewhere on the DOM (to follow natural `z-index` assignment).

As for the modal not opening again: which version of `strike_modal` are you using? One of the developers behind this component mentioned that this was a bug that was fixed in `0.8.0`.
