### ISSUE TITLE
Multiselect options should overlap "slds-scrollable" modal

### ISSUE THREAD

**Issue by up2go-rsoesemann** [appiphony/Strike-Components#64]
I am using a <c:strike_multiSelectPicklist> in a scrollable modal 

```
<div class="slds-modal__content slds-p-around_medium" id="modal-content-id-1">
	<div class="slds-scrollable">
        <ul class="slds-accordion">
            <aura:iteration items="{!v.attributes}" var="attribute">
                <c:strike_multiSelectPicklist label="Filter volumes by" value="{!attribute.filters}" onchange="{!c.changeFilters}" placeholder="{!attribute.label + ' - Select values'}">
                    <aura:iteration items="{!attribute.values}" var="value">
                        <c:strike_option label="{!value}" value="{!value}"/>
                    </aura:iteration>
                </c:strike_multiSelectPicklist>
            </aura:iteration>
        </ul>
    </div>
</div>
```

and I want the strike-options of the current focus to overlap the scrollable area to make them better visible. I have tried to add a overflow: visible basically everywhere but it doesn't work. 

<img width="683" alt="bildschirmfoto 2017-08-09 um 10 52 36" src="https://user-images.githubusercontent.com/8180281/29115407-dcff3d9c-7cf7-11e7-8117-a065e3cffe1c.png">

This looks like either a SLDS bug or a problem with Strike's implementation.

I don't want to edit the strike-options component but think you will need to apply the right CSS z-index property (or the right class) on the ui:scrollerWrapper component or below.

**Comment by up2go-rsoesemann** [comment]
I see many other issues responded or solved but nobody seems to touch this one :-(

**Comment by kevinberonilla** [comment]
Sorry about the delay, we're not ignoring you! We haven't been able to put a Visual Designer back on the Strike team for some time, so only some of the issues have been addressed. We will have a go at finding a solution for this soon.

**Comment by kevinberonilla** [comment]
So I've been thinking about this issue for the past few days and determined there isn't really an elegant solution to this. What we've done in the past is override the `slds-modal__content` class to be `overflow: visible`, which yields the desired result but this only works if the content does not take much vertical real estate, having no need to scroll. I will assume this is not ideal in your case, since you are utilizing accordions.

The only other way around this is for the component to move the dropdown element somewhere higher in its DOM ancestry (outside of the component's scope, to combat the modal content's `overflow`) and make it `position: fixed` with dynamic X and Y positioning. This, however, will not pass security review since it is considered DOM manipulation. We will always develop Strike components to be compliant with security guidelines since we use them ourselves in projects, so I can say with confidence that we can never implement this solution for an official Strike release.

If it's any consolation, Salesforce's own UI suffers from the same issue, and I'm willing to bet their designers and engineers have had this discussion already since they're using the same component framework as us.
![screen shot 2017-08-17 at 9 06 06 am](https://user-images.githubusercontent.com/8738640/29416461-c0685e22-832b-11e7-9053-decd856cf8b5.png)

**One last note:** is there a reason why you're using the `slds-scrollable` class inside of `slds-modal__content`? The `slds-modal__content` already has `overflow-y: auto`, which achieves the same thing as `slds-scrollable` vertically. You might be able to get away with removing the scrollable container. This would also fix the padding issue, where the is over the content and not the container.

**Comment by up2go-rsoesemann** [comment]
Thanks for digging into this. 

I also created an issue in the Lightning Design System repo https://github.com/salesforce-ux/design-system/issues/483
